### PR TITLE
init project

### PR DESCRIPTION
**Pull request by ruanzhuang22**
https://edu-redmine.sun-asterisk.vn/issues/49071?issue_count=35&issue_position=34&next_issue_id=49070&prev_issue_id=49072

### CODE REVIEW

**Comment by ruanzhuang22** [comment]
ready

**Comment by ruanzhuang22** [comment]
ready

**Comment by ruanzhuang22** [comment]
ready

**Review by ghost — COMMENTED** [review]
sửa lại version ruby

**Comment by ruanzhuang22** [comment]
ready

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
